# Generated by Django 3.2.10 on 2022-01-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withoutrestm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
