# Generated by Django 3.2.10 on 2022-01-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withoutrestm', '0002_alter_employee_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
