# Generated by Django 3.2.10 on 2021-12-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=None)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(default=None)),
            ],
        ),
    ]
